### ISSUE TITLE
Implement `audio` method

### ISSUE THREAD

**Issue by fabio-ivona** [defstudio/telegraph#185]
implement https://core.telegram.org/bots/api#sendaudio

to allow:

```php
Telegraph::audio($path, $title, $performer, $duration)
    ->thumb($thumbImagePath)
    ->silent()
    ->protected()
```

**Comment by VividhPandey003** [comment]
Hey, I am a beginner to Open Source and really looking forward to contribute to this repo. Could you please assign this issue to me

**Comment by fabio-ivona** [comment]
Hi, have you ever used our package?

**Comment by VividhPandey003** [comment]
Hii, You can just ignore my comment. I do not have knowledge to fix it right now. If someday I'm able to I'll come back to this repo to contribute. Thank You for giving me your time

**Comment by nicola-posa** [comment]
Hi, I'm implementing this one
