### ISSUE TITLE
Implement `videoNote` method

### ISSUE THREAD

**Issue by fabio-ivona** [defstudio/telegraph#186]
implement https://core.telegram.org/bots/api#sendvideonote

to allow:

```php
Telegraph::videoNote($path)
    ->thumb($thumbImagePath)
    ->silent()
    ->protected()
```

**Comment by VividhPandey003** [comment]
Dear @fabio-ivona , I am a beginner to Open Source and really looking forward to contribute to this repo. Could you please explain this issue to me and if I'm able to, assign this issue to me. As of now what I understood was I just have to add these 4 lines of code to implement videonote. Can you please tell me if I'm right or wrong. Also if I am correct, where can I find the code to make these changes. I'm a complete beginner, I'm really sorry if any of this doesn't make any sense to you.

**Comment by fabio-ivona** [comment]
Hi @VividhPandey003 

the 4 lines of code you see are the method to implement, several changes are to be made in order to obtain this

if you want an example you can see where video(), photo() and document() methods are defined:

https://github.com/defstudio/telegraph/blob/main/src/Concerns/SendsAttachments.php

**Comment by VividhPandey003** [comment]
Okay, yes I understand it now. I'll try to learn first. Thank you for explaining it to me and sorry😐😅

**Comment by elephantux** [comment]
What about this feature?

**Comment by fabio-ivona** [comment]
It's in our backlog, will be implemented soon
