### ISSUE TITLE
Implement `contact` method

### ISSUE THREAD

**Issue by fabio-ivona** [defstudio/telegraph#187]
implement https://core.telegram.org/bots/api#sendcontact

to allow:

```php
Telegraph::contact($phoneNumber, $firstName, $lastName, $vcard)
```

**Comment by tombenevides** [comment]
Hi, @fabio-ivona , I would like to work on this issue

**Comment by fabio-ivona** [comment]
Hi @tombenevides feel free to do it 😉

**Comment by alglyzin** [comment]
Now we also need a method.

**Comment by fabio-ivona** [comment]
@tombenevides any update? otherwise we can work this one
