### ISSUE TITLE
protect_content Parameter

### ISSUE THREAD

**Issue by ahr1384** [defstudio/telegraph#236]
In all send method in bot we can set protect_content but i don't find in package 
please add it 
![image](https://user-images.githubusercontent.com/87445571/198062027-b4291015-6f4c-4f59-ba50-88cf5763ac0e.png)

**Comment by ahr1384** [comment]
@fabio-ivona

**Comment by fabio-ivona** [comment]
->protected()

**Comment by ahr1384** [comment]
Thank You very much
