### ISSUE TITLE
how use switch_inline_query type in InlineKeyboardButton

### ISSUE THREAD

**Issue by ahr1384** [defstudio/telegraph#238]
InlineKeyboardButton has type switch_inline_query but in package not found this
I want make share button with switch_inline_query in another chat

![image](https://user-images.githubusercontent.com/87445571/198562558-7979aba3-f687-4722-8e06-783fc7496e2b.png)

**Comment by ahr1384** [comment]
https://core.telegram.org/bots/api#inlinekeyboardbutton
@fabio-ivona

**Comment by fabio-ivona** [comment]
implemented in #247

**Comment by ahr1384** [comment]
Thanks 💯
