### ISSUE TITLE
A single custom method to handle all Webhook commands

### ISSUE THREAD

**Issue by keyur555** [defstudio/telegraph#244]
Hello,

Is it possible to use a single custom webhook method to handle all commands? I currently don't like that you have to implement a new controller action for every command you want to add.

I think of it like this:

```php

class MyWebhookController extends WebhookHandler
{
    public function handleMyCommand()
    {
        // custom logic
        match ($command) {
            "start" => ....,
        }
    }
}

```

Thank you!

**Comment by fabio-ivona** [comment]
Hi @keyur555 you can obtain it this way

https://defstudio.github.io/telegraph/#unknown-commands

**Comment by keyur555** [comment]
> Hi @keyur555 you can obtain it this way
> 
> https://defstudio.github.io/telegraph/#unknown-commands

It works! Thank you!
