### ISSUE TITLE
Custom WebHook URL

### ISSUE THREAD

**Issue by alglyzin** [defstudio/telegraph#254]
I use a local Telegram Bot server. When registering, the WebHook is installed based on the APP_URL configuration variable. But my URL inside the server starts with http://127.0.0.1:8080 (for example).

As an option, make a separate option in the configuration.

**Comment by fabio-ivona** [comment]
Hi, I'm not sure if I got it: do you have an error when registering a webhook? (as you don't have an `HTTPS` url)

the url is generated from the route `telegraph.webhook`, is it missing also the `8080` port?

**Comment by alglyzin** [comment]
My bot lives locally on the server, there is no external access for it. Therefore, my WebHook looks like this http://localhost/telegraph/5655217470:AAGIuHqaMwuGVpbeNZ5JgXMqmpaTOk-iV-U/webhook

But my APP_URL is different, different from http://localhost

**Comment by alglyzin** [comment]
My bot lives locally on the server, there is no external access for it. Therefore, my WebHook looks like this http://localhost/telegraph/..../webhook

But my APP_URL is different, different from http://localhost/

**Comment by fabio-ivona** [comment]
Ok,il I got it, 

Soon I will add a config option to force a custom webhook url

**Comment by alglyzin** [comment]
Thanks. I really like your work)

**Comment by fabio-ivona** [comment]
@alglyzin implemented in #256 and released in a few minutes
