### ISSUE TITLE
Storing Information

### ISSUE THREAD

**Issue by alglyzin** [defstudio/telegraph#257]
I can place user related information in there and also easily access stored elements for the current chatbot user, that i are interacting with. For example:

`$this->userStorage()->save(['key' => $value]);`
`$this->userStorage()->get('key');`
`$this->userStorage()->all();`
`$this->userStorage()->delete();`

Data can be stored in json files. With this tool, it is very convenient to store intermediate data related to a specific user.

**Comment by fabio-ivona** [comment]
Hi, could you elaborate your request?

**Comment by alglyzin** [comment]
I need to store some data tied to users between requests. Here's more about what I meant: https://github.com/botman/docs/blob/master/storing-information.md

**Comment by fabio-ivona** [comment]
@alglyzin here's a PR implementing the data storage system, feel free to review the code and test it (you can require dev-user-storage version from composer)

will be released after some testing and reviewing by our other devs
