### ISSUE TITLE
Implement `sendReaction` Method

### ISSUE THREAD

**Issue by lucidlemon** [defstudio/telegraph#260]
https://core.telegram.org/method/messages.sendReaction

Allows bots to react to messages, useful to display that the bot understood a message and did something with it

Just checked, not yet available in official bot api:
https://github.com/tdlib/telegram-bot-api/issues/260

**Comment by DavePodosyan** [comment]
It's already in bot api
https://core.telegram.org/bots/api#setmessagereaction

Any plans on getting this available?

**Comment by MarioGattolla** [comment]
Implemented in #641
