### ISSUE TITLE
Errors in the documentation

### ISSUE THREAD

**Issue by ilysharusher** [defstudio/telegraph#262]
It's not cretitic, but a newbie like me will be stuck here for a long time :)
![chrome_Ue92ASaTKW](https://user-images.githubusercontent.com/64766878/202173682-ba7f31c6-37b3-4065-96bb-bc6978e234db.png)
![phpstorm64_2f5ZKYjaAz](https://user-images.githubusercontent.com/64766878/202173686-8c7e7c4e-1725-4b87-8d70-d9058b80af4c.png)

**Comment by stas12go** [comment]
![Снимок экрана_2022-11-16_19-08-58](https://user-images.githubusercontent.com/78864187/202203530-3e93c681-8278-4d7e-b867-e2040895ba38.png)
![Снимок экрана_2022-11-16_19-12-40](https://user-images.githubusercontent.com/78864187/202203537-1b31803a-ce81-493b-83a1-bf3839ab37ab.png)

**Comment by ilysharusher** [comment]
> Docs: ![Снимок экрана_2022-11-16_19-08-58](https://user-images.githubusercontent.com/78864187/202203530-3e93c681-8278-4d7e-b867-e2040895ba38.png) Real code (it means _Method 'action' not found in \DefStudio\Telegraph\Keyboard\ReplyButton_): ![Снимок экрана_2022-11-16_19-12-40](https://user-images.githubusercontent.com/78864187/202203537-1b31803a-ce81-493b-83a1-bf3839ab37ab.png)

I didn't understand it at first, either. It seems like callbackQuery only exists on the inline keyboard. 😂

**Comment by stas12go** [comment]
@ilysharusher did you find some kind of spare way?

**Comment by ilysharusher** [comment]
@stas12go I just started learning this library myself today) Well, in theory, a normal keyboard counts as a normal text. No actions can be there, so just a typo in the documentation I guess.

**Comment by stas12go** [comment]
@ilysharusher thanks for thinking.

**Comment by fabio-ivona** [comment]
@ilysharusher thanks for pointing this out! We are fixing the documentation and updating it soon

**Comment by ilysharusher** [comment]
@fabio-ivona And it would be nice to make a reference of " $this->chat-> " in the documentation to send a request to this chat immediately. Because finding this feature in an extensions class can be a problem for many people...

**Comment by fabio-ivona** [comment]
> @fabio-ivona And it would be nice to make a reference of " $this->chat-> " in the documentation to send a request to this chat immediately. Because finding this feature in an extensions class can be a problem for many people...

@ilysharusher would you mind to open a separate PR for this one? We'll implement it soon 😉
