### ISSUE TITLE
Need regex for Telegram Markdownv2-style for message content

### ISSUE THREAD

**Issue by uzdeveloper1** [defstudio/telegraph#269]
<img width="1480" alt="Screenshot 2022-11-23 at 21 39 41" src="https://user-images.githubusercontent.com/65232715/203601049-44d9d6fe-8c0c-4042-96cb-d348112135b7.png">

**Comment by fabio-ivona** [comment]
Hi @uzdeveloper1 !

could you elaborate your request?

**Comment by fabio-ivona** [comment]
@uzdeveloper1 we found the issue, we are releasing a fix, now markdown v2 will be an opt-in feature

escaping will still be in charge of the developer

ref #273
