### ISSUE TITLE
Error in the configuration path

### ISSUE THREAD

**Issue by alglyzin** [defstudio/telegraph#274]
https://github.com/defstudio/telegraph/blob/17a0a0f31de30292371650c91745d47c44d20eab/src/Concerns/InteractsWithWebhooks.php#L17

**Comment by alglyzin** [comment]
Сorrectly
`$customWebhookUrl = config('telegraph.custom_webhook_domain'); `

**Comment by fabio-ivona** [comment]
fixed, thanks!
