### ISSUE TITLE
How to handle ReplyKeyboard's button with request_contact?

### ISSUE THREAD

**Issue by ChillMouse** [defstudio/telegraph#285]
Hello, I tried to handle message in chat, but isn't working.

How to get contact from users with ReplyKeyboard?

Can you give me advice, please?

**Comment by ChillMouse** [comment]
Sorry, move me to  discussions

**Comment by ChillMouse** [comment]
I saw your response for #181 , but isn't secure, because I can send to my bot manually contact from my smartphone. How I can do it serurely?

**Comment by ChillMouse** [comment]
Okay, guys, I hope what you lot found my ask in Google... Okay, I found answer for my question.

We can "message", and "message" have got a lot of options, e. g. "from"->"id" and 'contact'->'userId'

If this parameters is assert --- then author of message gave our correct phoneNumber!!!

`    protected function handleChatMessage(Stringable $text): void
    {
        $phone = $this->message->contact()->phoneNumber();
        $userId = $this->message->contact()->userId();
        $verifyUserId = $this->message->from()->id();
        $isVerifyPhone = intval($userId == $verifyUserId);
        $this->chat->html("Received: $phone, $userId, $verifyUserId, total: $isVerifyPhone")->send();
    }`

**Comment by fabio-ivona** [comment]
Hi great suggestion, will merge your documentation contribution in #286 so this will be available to others
