### ISSUE TITLE
No TelegraphChat defined for this request

### ISSUE THREAD

**Issue by niravbhoi** [defstudio/telegraph#314]
I am using webhook handler and exploring how to use Telegraph facade. I am using Laravel
When I try to send simple hello world message in my log it shows : No TelegraphChat defined for this request

I want to use differant methods of Telegram Bot APi which are not listed in your documentation. How can I achive that?

`use DefStudio\Telegraph\Facades\Telegraph as TelegraphFacade;`

`class CustomWebhookHandler extends WebhookHandler`
`{`
`public function start()
    {
    TelegraphFacade::message('hello world')->send();
    }`
`}`

**Comment by fabio-ivona** [comment]
Just use $this->reply('hello word')

**Comment by niravbhoi** [comment]
> Just use $this->reply('hello word')

@fabio-ivona I want to use reply keyboard In doc I am unable to find how to bind with $this as you suggested.
It is possible to use Telegraph facade in webhook? and how?

**Comment by niravbhoi** [comment]
resolved issue :
I can pass like :
`$this->chat->message('select options')`
            `->replyKeyboard(ReplyKeyboard::make()->buttons([`
                `ReplyButton::make('foo')->requestPoll(),`
                `ReplyButton::make('bar')->requestQuiz(),`
                `ReplyButton::make('baz')->webApp('https://webapp.dev'),`
            `]))->send();`
