### ISSUE TITLE
Can't use Keyboard at the same time

### ISSUE THREAD

**Issue by ahr1384** [defstudio/telegraph#332]
Hi
I can't use keyboard and replykeyboard at the same time, this is because of the wrong structure in the arrays

**Comment by ahr1384** [comment]
Here:
![image](https://user-images.githubusercontent.com/87445571/216972508-aa7e0a5b-5d94-4d1c-93c2-85c5dc23f58e.png)
![image](https://user-images.githubusercontent.com/87445571/216972524-35873042-b9b1-4a0c-94fb-474138fc88e0.png)

**Comment by ahr1384** [comment]
It should be something like this:
![image](https://user-images.githubusercontent.com/87445571/216972702-edf7cf6d-56a6-4b42-b56b-7ce53f4c30b2.png)
![image](https://user-images.githubusercontent.com/87445571/216972815-5f23178d-50ff-4cf5-bff2-152e16cca130.png)

**Comment by ahr1384** [comment]
plz fix it: @fabio-ivona

**Comment by fabio-ivona** [comment]
fixed

**Comment by ahr1384** [comment]
Tnx
