### ISSUE TITLE
documentation (webhooks-callback-reply)

### ISSUE THREAD

**Issue by moayedlaravel** [defstudio/telegraph#349]
in documentation 
(https://defstudio.github.io/telegraph/webhooks/callback-reply)

$this->reply('plapla')->send();  // error

$this->reply('plapla'); // ok

![image](https://user-images.githubusercontent.com/118882102/221323040-abfaa381-35de-42b6-917d-654298833427.png)

**Comment by fabio-ivona** [comment]
fixed
