### ISSUE TITLE
RTL Keyboard Buttons Position

### ISSUE THREAD

**Issue by sadegh19b** [defstudio/telegraph#363]
I prefer using keyboards, but I am unable to position using the right-to-left (RTL) buttons. Is it possible to include an option to use the RTL keyboard button position?

Thanks

**Comment by fabio-ivona** [comment]
@sadegh19b feel free to open a PR for it 👍

**Comment by sadegh19b** [comment]
@fabio-ivona Thank you for your attention. I wanted to let you know that I have been working on adding right-to-left (RTL) support for the keyboard and have submitted a pull request to this repository (#364). I would greatly appreciate it if you could review my changes, and if they are acceptable, we can mark this issue as complete.
