### ISSUE TITLE
Invite link that has been used to join group

### ISSUE THREAD

**Issue by pm-12** [defstudio/telegraph#365]
When using **handleChatMemberJoined** is there a way to figure out what invite link was used to join the group?

**Comment by fabio-ivona** [comment]
Sadly, this is not supported by Telegram bots APIs

the only place where you have info about the invite link is for pending join requests

**Comment by pm-12** [comment]
@fabio-ivona Thanks for your quick reply!

Would it be possible to perhps grab it from here:

https://core.telegram.org/bots/api#chatmemberupdated
it has a invite_link field in there.

Or is this also for join requests?
