### ISSUE TITLE
How to store/download incoming chat photo/audio/video etc?

### ISSUE THREAD

**Issue by elephantux** [defstudio/telegraph#366]
I can see the methods in the source code, but can't figure out how to use them. Could someone please show me an example code to save a photo?

**Comment by fabio-ivona** [comment]
if you have a file id, you can store with:

```php
Telegraph::bot($yourBot)->store($fileId, Storage::path('your/file/path'));
```

otherwise, from a message (comping from a webhook or update polling):

```php
/** @var DefStudio\Telegraph\DTO\Message $message
Telegraph::bot($yourBot)->store($message->video(), Storage::path('your/file/path'));
```

**Comment by elephantux** [comment]
@fabio-ivona thank you, that helped! 

Is there any way to identify the type of content sent? Or do I need to check all types?

**Comment by fabio-ivona** [comment]
> Is there any way to identify the type of content sent? Or do I need to check all types?

no, currently there's no a built-in way to do this in a quickly
