### ISSUE TITLE
How to handle answer of user to ReplyButton ?

### ISSUE THREAD

**Issue by Odilbukh** [defstudio/telegraph#370]
I have ReplyKeyboard and ReplyButton. How can I know wich button was clicked ?
Generaly how to handle user message or answer in ReplyButton ? How to listen for the button text, that is sent when the user clicks on the button?

![image](https://github.com/defstudio/telegraph/assets/22895615/4fcc51c7-e20b-4e77-acc0-31e3e8fa4746)

**Comment by fabio-ivona** [comment]
@Odilbukh you usually should add a parameter to each button:

```php
Button::make('Delete')->action('delete')->param('item_id', 2)
```

And use these data to handle inside a WebhookHandler method

**Comment by musobekmadrimov** [comment]
> @Odilbukh you usually should add a parameter to each button:
> 
> ```
> Button::make('Delete')->action('delete')->param('item_id', 2)
> ```
> 
> And use these data to handle inside a WebhookHandler method

In ReplyButtons there is not action method?

**Comment by fabio-ivona** [comment]
@Odilbukh just listen for the message sent when the button is clicked and check its content

**Comment by fabio-ivona** [comment]
@musobekmadrimov my fault, was replying for standard buttons, did not notice the subjects was a ReplyKeyboard
