### ISSUE TITLE
Queued Messages response

### ISSUE THREAD

**Issue by elephantux** [defstudio/telegraph#372]
When message sent with [queue](https://defstudio.github.io/telegraph/features/queued-messages) it's not possible to get server response after Job finished. For example to get file_id or message_id from telegram api response for later use.

Is there a solution?

I want to use queues when the bot needs to send a message with a delay.

**Comment by elephantux** [comment]
I found a workaround by creating my own job. But maybe it would be nice to refactor SendRequestToTelegramJob to return the results of post request.

**Comment by fabio-ivona** [comment]
@elephantux feel free to open a PR for this
