### ISSUE TITLE
I am using laravel. And when I send multiple messages in sequence sometimes the message gets delayed for 5 seconds.

### ISSUE THREAD

**Issue by cc-niravbhoi** [defstudio/telegraph#382]
I am using laravel. And when I send multiple messages in sequence sometimes the message gets delayed for 5 seconds.
Any solutions on that?

```
public function start(){
     $this->chat->message('')->chatAction(ChatActions::TYPING)->send();
     $this->chat->message('Hello')->send(); 
     $this->chat->message('this is my message to world')->send();
}
```

_Originally posted by @cc-niravbhoi in https://github.com/defstudio/telegraph/discussions/381_

**Comment by fabio-ivona** [comment]
I am not aware of any throttling by telegram for so few messages

Could you share a sample repository that reproduces the issue?

**Comment by cc-niravbhoi** [comment]
Hi @fabio-ivona 
I have shared the code. This is the message I am sending to the user from Webhook. 
If I hit /start from telegram multiple times then it will get stuck for 5 seconds and then sends the message.
Let me know If you didn't get it. I will create repo.
