### ISSUE TITLE
Support multiple bots

### ISSUE THREAD

**Issue by cschalenborgh** [defstudio/telegraph#387]
Hi,

First of all, great library, thanks!

I managed to write 1 bot that communicates through a webhook. 
But what's the recommended approach to handle / listen to multiple bots with webhooks? Or is this only possible through (manually) polling the bots?
Any chance you have a code sample handling multiple bots?

Thanks!

**Comment by fabio-ivona** [comment]
Hi, telegraph supports multiple bots for webooks, the setup is the same, you should just register the webook for each of them and telegraph will take care of retrieving the right bot

**Comment by andrey-helldar** [comment]
@fabio-ivona,

You can register more than one, but you can only specify [one handler](https://github.com/defstudio/telegraph/blob/main/config/telegraph.php#L24) in the settings.

I am also interested in the possibility of using different handlers for different bots.

At the moment my handler file looks something like this:
```php
<?php

declare(strict_types=1);

namespace App\Http\Webhooks;

use App\Enums\BotName;
use DefStudio\Telegraph\Handlers\WebhookHandler;
use Illuminate\Support\Str;

class TelegraphHandler extends WebhookHandler
{
    public function start(): void
    {
        foreach ($this->handlers() as $bot => $handler) {
            if ($this->toAll() || $this->toBot($bot)) {
                $this->run($handler, 'start');
            }
        }
    }

    protected function run(BaseHandler|string $handler, string $command): void
    {
        (new $handler)->{$command}($this->bot, $this->chat, $this->message);
    }

    protected function toAll(): bool
    {
        return ! Str::contains($this->message->text(), '@');
    }

    protected function toBot(string $bot): bool
    {
        return Str::endsWith($this->message->text(), '@' . $bot);
    }

    protected function handlers(): array
    {
        return [
            BotName::Foo->value => FooHandler::class,
            BotName::Bar->value => BarHandler::class,
        ];
    }
}
```

**Comment by fabio-ivona** [comment]
@andrey-helldar I think your solution is a good way to achieve what you need

**Comment by andrey-helldar** [comment]
@fabio-ivona, due to the lack of an out-of-the-box solution, yes :)

I can suggest changing the logic of processing the "webhook_handler" key to the following:

1. If a reference to the handler class is specified in the value, all requests are sent to it. This is implemented now.
2. If the value specifies an array, then use the bot name as the key and a reference to the handler as the value. In this case you can also set a parameter, for example, "default" and send requests for undefined bots to it. And if the "default" key is not specified, the requests will not be redirected anywhere.

For example:
```php
// default logic
return [
    'webhook_handler' => DefStudio\Telegraph\Handlers\EmptyWebhookHandler::class,
];

// custom logic
return [
    'webhook_handler' => [
        'foo_bot' => DefStudio\Telegraph\Handlers\FooBotHandler::class,
        'bar_bot' => DefStudio\Telegraph\Handlers\BarBotHandler::class,

        // This handler will handle requests that were not matched by previous bots.
        'default' => DefStudio\Telegraph\Handlers\EmptyWebhookHandler::class,
    ]
];

// or
return [
    'webhook_handler' => [
        'foo_bot' => DefStudio\Telegraph\Handlers\FooBotHandler::class,
        'bar_bot' => DefStudio\Telegraph\Handlers\BarBotHandler::class,
    ]
];
```

**Comment by fabio-ivona** [comment]
I see your point, but this may lead to some issues: what if you change your bot name?

**Comment by cschalenborgh** [comment]
I've solved it by adding a new column to the telegraph_bots table which I can then use to dynamically specify the handler class.

```
class TelegramController extends WebhookHandler
{
    /**
     * @param Request $request
     * @param TelegraphBot $bot
     */
    public function handle(Request $request, TelegraphBot $bot): void
    {
        $handler = empty($bot->class) ? DefaultBot::class : "App\Services\Bots\\$bot->class";
        $handler = app($handler);
        $handler->handle($request, $bot);
    }
}
```

**Comment by andrey-helldar** [comment]
You can also improve based on the bot's name:
```php
class TelegramController extends WebhookHandler
{
    public function handle(Request $request, TelegraphBot $bot): void
    {
        $class = 'App\Services\Bots\\' . $bot->name;
        
        $handler = class_exists($class) ? $class : DefaultBot::class;

        app($handler)->handle($request, $bot);
    }
}
```

**Comment by andrey-helldar** [comment]
Another option:

```php
// config/telegraph.php
return [
    'webhook' => [
        'handler' => App\Http\Webhooks\Handler::class,
    ]
];
```
```php
namespace App\Http\Webhooks;

use DefStudio\Telegraph\Handlers\WebhookHandler;
use DefStudio\Telegraph\Models\TelegraphBot;
use Illuminate\Http\Request;

class Handler extends WebhookHandler
{
    protected array $handlers = [
        'bot_1' => Bot1Handler::class,
        'bot_2' => Bot2Handler::class,
        // ...other handlers...
    ];

    public function handle(Request $request, TelegraphBot $bot): void
    {
        $handler = $this->getHandler($bot->name);

        /** @var WebhookHandler $instance */
        $instance = app($handler);

        $instance->handle($request, $bot);
    }

    protected function getHandler(string $botName): string
    {
        return $this->handlers[$botName] ?? DefaultBot::class;
    }
}
```

**Comment by andrey-helldar** [comment]
> I see your point, but this may lead to some issues: what if you change your bot name?

I see the message has gone unanswered. I can't say about others, but in my case if I change the bot name, I will get an error when running unit tests, because the new name will be missing in the Enum class. I wrote the examples above in text for easier reading.

Besides, Telegram is so organized that bots cannot change their names - only delete the old one and create a new one.

Therefore, when replacing a bot, you will have to register a new one or replace an existing one, which means that unit tests will again return an error if something is done incorrectly or incompletely :)

Translated with DeepL.com (free version)
