### ISSUE TITLE
Bot keeps sending messages endlessly

### ISSUE THREAD

**Issue by msehome** [defstudio/telegraph#398]
I am using a custom handler for webhook and everything seems to be working.
As soon as I call a function (a custom function called by a button action) the bot starts sending the same message over and over again endlessly. I have to wait until it stops. 
Even deleting the webhook and creating it again will not help and as soon as the webhook is created the messages continue to be sent.

Any idea?

**Comment by fabio-ivona** [comment]
No idea, sorry, could you try to put some logs in order to detect what triggers the repeated message?

**Comment by msehome** [comment]
I just discovered the issue, there was a function running inside the main function which lead to an exception. Despite the fact that the exception was handled I guess there was a certain exception that was not handled maybe. The exception caused the process to go astray and the main function probably wouldn't send 200 ok back to the Telegram API and the Telegram API kept sending the same message back to my app.

**Comment by fabio-ivona** [comment]
are you able to reproduce the issue? will be helpful for fixing it

**Comment by msehome** [comment]
Of course
Just create a button action, then in the action function call another
function. In the second function produce an error.
For example use an array as a string.
This was the issue in my case. The variable was initiated as a string but
used as an array mistakenly.

**Comment by fabio-ivona** [comment]
Thanks!
 
we'll release a fix soon

**Comment by MrFallen** [comment]
I have same problem when I push action button and close Telegram App. I can record video.

**Comment by msehome** [comment]
You have to handle all errors otherwise this will happen again.

**Comment by fabio-ivona** [comment]
fixed
