### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by snake302** [defstudio/telegraph#404]
Hello,

Just wanna report that documentation missing three things:

1) Delete message method [mentioned there ](https://defstudio.github.io/telegraph/features/messages)
2) DefStudio\Telegraph\DTO\Chat [mentioned in the DTO message -> chat()](https://defstudio.github.io/telegraph/webhooks/dto/)
3) Anchor links are broken everywhere

**Comment by fabio-ivona** [comment]
Hi! Thanks for pointing this out!

We are making a complete documentation rebuild, will take this into account ♥️

**Comment by adityaa-codes** [comment]
It Seems like whole documentation is missing

**Comment by fabio-ivona** [comment]
Fixed by @jorisdrenth 🙌

**Comment by fabio-ivona** [comment]
Sorry, was referring to the broken docs, will handle the rest in the next release

**Comment by jorisdrenth** [comment]
> We are making a complete documentation rebuild, will take this into account ♥️

Any news on this? If you're interested, I was playing around with Nuxt a little bit and have a branch with Nuxt 3 + [Docus](https://nuxt-themes.netlify.app/themes/docus/) for the Telegraph docs.

**Comment by fabio-ivona** [comment]
We are going to add the documentation to def:studio website (laravel)

But meanwhile it would be great to try your nuxt + docus build

**Comment by jorisdrenth** [comment]
Cool. Will polish it up a bit and let you know when I committed the code.

**Comment by fabio-ivona** [comment]
@snake302  fixed in , let me know if anything is still flacky
