### ISSUE TITLE
DTO\User loses is_bot=false property when call ...->toArray() method

### ISSUE THREAD

**Issue by varemel** [defstudio/telegraph#416]
Hello,

When call `DTO\User` object toArray() method `is_bot = false` property is missing. `array_filter()` removes false values from array.

`vendor/defstudio/telegraph/src/DTO/`
```
public function toArray(): array
    {
        return array_filter([
            'id' => $this->id,
            'is_bot' => $this->isBot,
            'first_name' => $this->firstName,
            'last_name' => $this->lastName,
            'username' => $this->username,
            'language_code' => $this->languageCode,
        ]);
    }
```
<img width="911" alt="Screenshot 2023-10-12 at 01 52 32" src="https://github.com/defstudio/telegraph/assets/84812777/79148cd2-296c-49b6-a4c9-bcd8f7c978eb">

<img width="1057" alt="Screenshot 2023-10-12 at 01 57 28" src="https://github.com/defstudio/telegraph/assets/84812777/776de4c9-06c8-4d68-b1e2-aa6e680ab690">

**Comment by fabio-ivona** [comment]
fixed in #502
