### ISSUE TITLE
chatMember method not exist

### ISSUE THREAD

**Issue by esmaei1** [defstudio/telegraph#421]
get error when call chatMember method : 
When I try this:
```
$chat =  TelegraphChat::where('chat_id', '-1001917277777')->first();
$chat->chatMember('367389764')->send();
```
I get this error:

`local.ERROR: Call to undefined method DefStudio\Telegraph\Models\TelegraphChat::chatMember() `

**Comment by MarioGattolla** [comment]
Hi , you can now use the memberInfo() method
