### ISSUE TITLE
SELF-SIGNED CERTIFICATE ISSUE

### ISSUE THREAD

**Issue by Asekir** [defstudio/telegraph#437]
Hi,
I'm working with telegraph and I need some  clarifications.
After I created the bot I associated it with telegram bot through the token, after I associated the chat and at the end I wanted associate a webhook at the bot; here I had some issues.
When I launched the command
php artisan telegraph:set-webhook
I saw this error
![image](https://github.com/defstudio/telegraph/assets/69391511/b4095edb-30b9-4c5d-8722-e7fc3a84931f)
I tried to change the SSL certificate but I had the same issue; I set correctly the APP_URL in the env file with a https link.
I solved the issue disabling the CURLOPT_SSL_VERIFYPEER option in the class CurlFactory.php in this way
![image](https://github.com/defstudio/telegraph/assets/69391511/c1720923-3234-43a3-8055-3e9ae31a4720)
I supposed the SELF-SIGNED CERTIFICATE error is given when the firewall and the telegram server exchange their certificates; is it correct? Is it possibile write in the guide a page about the communication?
Thank you for your attention

**Comment by fabio-ivona** [comment]
Hi, I think this issue is not tied to Telegraph itself, you should refer to curl documentation
