### ISSUE TITLE
How to send large videos using Telegraph?

### ISSUE THREAD

**Issue by RamSen-IT** [defstudio/telegraph#470]
Hello!
I've been working on a bot that would send users videos (mostly larger than 500mb). I've read the telegram bot api docs. There is a restriction of 50MB, with videos/animations/documents. In the recent changes, Telegram announced now bots can send files upto 2000 MB.

I tried to do it with Telegraph::video, but it didn't work.

There are many bots that are uploading files upto 2GB, So, my question is how to do it?

**Comment by fabio-ivona** [comment]
I'm still seeing a 50mb limit on video size

https://core.telegram.org/bots/api#sendvideo

Could you paste a link to the source of your information?

**Comment by fabio-ivona** [comment]
Hmm, I think we could tune the file size check when the bot server is not the standard one

Will be added in next release

**Comment by RamSen-IT** [comment]
Yes, I would be very grateful for this feature

I'll be waiting :)

**Comment by fabio-ivona** [comment]
fixed in #476
