### ISSUE TITLE
When more than one user stops working

### ISSUE THREAD

**Issue by m-petrosyan** [defstudio/telegraph#496]
If there is only one user in the database everything is fine, but when there are two of them I get an error  when calling the Telegraph::photo('https://my-repository/photo.jpg')->send() method;

I get the following error in the log file
```
 No TelegraphChat defined for this request {"exception":"[object] (DefStudio\\Telegraph\\Exceptions\\TelegraphException(code: 0): No TelegraphChat defined for this request at C:\\wamp64\\www\\projects\\movie-telegram-bot\\vendor\\defstudio\\telegraph\\src\\Exceptions\\TelegraphException.php:16)
[stacktrace]
```

**Comment by fabio-ivona** [comment]
If there are two chats registered in your system, you should specify which one should receive your message through ->chat() method

**Comment by m-petrosyan** [comment]
Do I understand correctly that this is how it should work?
`Telegraph::chat(chat id))->photo($pathToPhotoFile)->send();`
