### ISSUE TITLE
No TelegraphChat defined for this request 

### ISSUE THREAD

**Issue by HamasakiBrain** [defstudio/telegraph#504]
My code is working when 1 chat in Database. When i send message on my bot from other account telegraph report No telegraphChat defined for this request. 
My handler on screen 1.
![image](https://github.com/defstudio/telegraph/assets/43117784/1f7d0148-9b01-4b41-9ab9-bb1a8e2f2b37)

My telegraph config file.
![image](https://github.com/defstudio/telegraph/assets/43117784/08cfe586-6d91-4206-aeb1-23f08298f2db)

**Comment by HamasakiBrain** [comment]
@fabio-ivona help please)

**Comment by fabio-ivona** [comment]
@HamasakiBrain could you check the value of `$this->chat` ?

**Comment by HamasakiBrain** [comment]
> @HamasakiBrain could you check the value of `$this->chat` and paste here your error stacktrace?

![image](https://github.com/defstudio/telegraph/assets/43117784/0cf0b3fc-1721-44b4-ac15-43ca721178cf)
![image](https://github.com/defstudio/telegraph/assets/43117784/3f9fe7ee-aa2c-4aed-a35a-e41e0d4e490e)


When ` Log::debug($this->chat);`
` Typed property DefStudio\Telegraph\Handlers\WebhookHandler::$chat must not be accessed before initialization`

**Comment by HamasakiBrain** [comment]
@fabio-ivona

**Comment by fabio-ivona** [comment]
@HamasakiBrain the exception triggers in app/Telegram/Service.php

so it's outside Telegraph source code

probably you are calling telegraph API that requires a chat to be set up, you should do i

**Comment by HamasakiBrain** [comment]
@fabio-ivona  I've removed this code, but it doesn't work without it. No TelegraphChat defined for this request

**Comment by fabio-ivona** [comment]
what code did you removed?

**Comment by HamasakiBrain** [comment]
> what code did you removed?

`$this->service->reading()`

**Comment by fabio-ivona** [comment]
So, now, what is the updated stack trace?

**Comment by HamasakiBrain** [comment]
> So, now, what is the updated stack trace?

The same mistake remained.  No TelegraphChat defined for this request

**Comment by fabio-ivona** [comment]
Sorry @HamasakiBrain ,can't help anymore without proper info

The previous stack trace triggered in one of your classes, now that you removed that call, I need the new stack trace in order to detect where the issue is triggered
