### ISSUE TITLE
Cannot use session() helper to store data in custom WebHooks handler 

### ISSUE THREAD

**Issue by jialeee17** [defstudio/telegraph#530]
In the custom WebHooks handler, I try to store some data via the Laravel "session()" global helper function but it didn't work as expected. There's no session was created. For example,

`
    public function connect()
    {
        try {
            session(['data' => '123']);
        } catch (Exception $e) {
            Log::channel('telegram')->error($e->getMessage());
            $this->chat->html(ChatService::error())->send();
        }
    }
`

**Comment by fabio-ivona** [comment]
Already answered in discussions
