### ISSUE TITLE
How to set multiple webhook handler

### ISSUE THREAD

**Issue by MdBayzidAman** [defstudio/telegraph#532]
Hello 👋,
With Telegraph here has features to add multiple bots, but **how can I handle webhooks for multiple bots?**
I can set only one webhook handler in config.

**Comment by DavePodosyan** [comment]
Also interested in this 👀

**Comment by MdBayzidAman** [comment]
It will be awesome if we can handle multiple bots in a single application.

**Comment by fabio-ivona** [comment]
When your handler differs for each bots you could override the handler to detect the bot and calling a dedicated handler for it

I think I'll write something about it in documentation soon, thanks for pointing this out

**Comment by ivankuraev** [comment]
> Hello 👋, With Telegraph here has features to add multiple bots, but **how can I handle webhooks for multiple bots?** I can set only one webhook handler in config.

If it's still relevant to you
https://github.com/defstudio/telegraph/discussions/552#discussioncomment-8788767

**Comment by MdBayzidAman** [comment]
@ivankuraev 
Yes! Thank you.
