### ISSUE TITLE
Keyboard::fromArray() method doesn't restore switch_inline_query & switch_inline_query_current_chat properties

### ISSUE THREAD

**Issue by varemel** [defstudio/telegraph#533]
Hi, 

When trying to restore keyboard from array `switch_inline_query` & `switch_inline_query_current_chat` properties are missing.
Suggest to add this to Keyboard::fromArray() method https://github.com/defstudio/telegraph/blob/722d94f83790fef66bb940b57f7b7e9f255d2acc/src/Keyboard/Keyboard.php#L60 

```php
if (array_key_exists('switch_inline_query', $button)) {
    $rowButton = $rowButton->switchInlineQuery($button['switch_inline_query']);
}

if (array_key_exists('switch_inline_query_current_chat', $button)) {
    $rowButton = $rowButton->switchInlineQuery($button['switch_inline_query_current_chat'])->currentChat();
}
```

**Comment by Freshblood1121** [comment]
My buttons are not showing up at all, please help...
Telegraph::message('hello world')
->keyboard(Keyboard::make()->buttons([
        Button::make('Delete')->action('delete')->param('id', '42'),
        Button::make('open')->url('https://test.it'),
        Button::make('Web App')->webApp('https://web-app.test.it'),
        Button::make('Login Url')->loginUrl('https://loginUrl.test.it'),
]))->send();

or

$this->chat->message('uh')->keyboard(Keyboard::make()->buttons([
            Button::make('i')->url('google.com'),
            Button::make('1')->url('google.com'),
            Button::make('e')->url('google.com'),
        ]))->send();
        
        All this gives one error:((((

![Снимок экрана 2024-02-25 071502](https://github.com/defstudio/telegraph/assets/59627636/5b6a14cf-7623-4190-aa35-20c9e9d97830)

**Comment by fabio-ivona** [comment]
Hi @varemel, thanks for your suggestion!

Feel free to open a PR for this

**Comment by fabio-ivona** [comment]
Thanks!
