### ISSUE TITLE
Keyboard and Buttons

### ISSUE THREAD

**Issue by Freshblood1121** [defstudio/telegraph#534]
My buttons are not showing up at all, please help...
Telegraph::message('hello world')
->keyboard(Keyboard::make()->buttons([
Button::make('Delete')->action('delete')->param('id', '42'),
Button::make('open')->url('https://test.it'),
Button::make('Web App')->webApp('https://web-app.test.it'),
Button::make('Login Url')->loginUrl('https://loginUrl.test.it'),
]))->send();

or

$this->chat->message('uh')->keyboard(Keyboard::make()->buttons([
Button::make('i')->url('google.com'),
Button::make('1')->url('google.com'),
Button::make('e')->url('google.com'),
]))->send();

    All this gives one error:((((
![Снимок экрана 2024-02-25 071502](https://github.com/defstudio/telegraph/assets/59627636/9297f057-5dc5-49c5-974f-9bd86c99bbf7)

**Comment by fabio-ivona** [comment]
You should have an entry in your laravel logs, could you check?

**Comment by Freshblood1121** [comment]
@fabio-ivona my error:

[2024-02-25 09:58:28] local.DEBUG: Telegraph webhook message {"text":"/hello"} 
[2024-02-25 09:58:28] local.INFO: {"ok":false,"error_code":400,"description":"Bad Request: BOT_DOMAIN_INVALID"}

**Comment by fabio-ivona** [comment]
What's your app domain? You need a valid https url

**Comment by Freshblood1121** [comment]
Oh, I needed to activate "**inline mode**, solved<3
