### ISSUE TITLE
 how to delete messages without blur effect?

### ISSUE THREAD

**Issue by AntonNosovich** [defstudio/telegraph#546]
Can i do it?

**Comment by fabio-ivona** [comment]
sorry, could you elaborate? what do you mean with "blur"?

**Comment by AntonNosovich** [comment]
> Can i do it?



> sorry, could you elaborate? what do you mean with "blur"?

 I mean this effect 

Uploading IMG_2086.MOV…

**Comment by fabio-ivona** [comment]
I don't think it is allowed by telegram APIs, sorry
