### ISSUE TITLE
How to get user  reply on message

### ISSUE THREAD

**Issue by AntonNosovich** [defstudio/telegraph#561]
$this->chat->message("text")->forceReply()->send();
How get answer on this message

**Comment by fabio-ivona** [comment]
You should listen for a reply in a webook

**Comment by AntonNosovich** [comment]
> You should listen for a reply in a webook

I can get each message ,but I need get only reply on bot message

**Comment by fabio-ivona** [comment]
Telegram is stateless, but you could keep track of the conversation status using telegraph internal storage system, eg.

Send your message

Record 'waiting for reply from user X'

Listen for incoming messages for a message from user X, checking his id against your stored one 

Handle the message and delete the storage record
