### ISSUE TITLE
replyWebhook() performance issue

### ISSUE THREAD

**Issue by ah-rahimi** [defstudio/telegraph#568]
Hi 
why `replyWebhook()` function in `TelegraphBot` model send a query for get all users?
![image](https://github.com/defstudio/telegraph/assets/87445571/c1d62785-6519-431c-8d4c-bda8c8574433)

in the `bot()` function get all chats (users) to check chat is set:
![image](https://github.com/defstudio/telegraph/assets/87445571/41388db9-0f29-463b-894f-60b86b21f695)

why query to the database and get all users?
We have a lot of users and that's too bad.

Please remove this, as there is no need for chat in the `replyWebhook()` function:
![image](https://github.com/defstudio/telegraph/assets/87445571/4c6b7039-66d8-4a16-8468-199b3b872ffe)

Thanks!

**Comment by ah-rahimi** [comment]
Can you check this @fabio-ivona?
We really have a performance problem...

**Comment by fabio-ivona** [comment]
fixed

**Comment by ah-rahimi** [comment]
Hello @fabio-ivona ,
I want to know why chat is needed here?

And now you send two queries.

**Comment by fabio-ivona** [comment]
That function automatically loads the chat when a bot has just one

it sends one query to count the bot's chats, if there are more than one, it should not send the second query

**Comment by ah-rahimi** [comment]
Yes, you are right.
But isn't it better to use a chat only where it is needed?
Even the count query is heavy.

**Comment by fabio-ivona** [comment]
I get your point and found a solution

let me know if v1.43.1 solves your issue

**Comment by ah-rahimi** [comment]
thank you so much
I will definitely let you know...
