### ISSUE TITLE
404 File not found | The documentation site does not open. 

### ISSUE THREAD

**Issue by wdecision21** [defstudio/telegraph#572]
The documentation site does not open.
https://defstudio.github.io/telegraph/
(https://github.com/defstudio/telegraph/assets/166806301/075d09cc-ec02-4682-acef-27aae415383f)

**Comment by andrey-helldar** [comment]
It’s so bad 🙁

**Comment by fabio-ivona** [comment]
and we are online :)

just a draft version, we'll improve it in the next days (side-navigation, search)

we have re-built all from scratch in PHP

**Comment by andrey-helldar** [comment]
@fabio-ivona, hmm…

![IMG_1164](https://github.com/defstudio/telegraph/assets/10347617/63ed9b25-ec4c-4ec6-b444-72e99e1d3454)
