### ISSUE TITLE
Actions in Handler

### ISSUE THREAD

**Issue by Freshblood1121** [defstudio/telegraph#604]
Hello!
Please tell me, if I create a button with the OpenFile action, then it can only be activated from Handler. 
Is it possible to make an action from other controllers?

![one](https://github.com/defstudio/telegraph/assets/59627636/6f20ce06-8978-499a-9e0d-4750b8f9b82b)

![two](https://github.com/defstudio/telegraph/assets/59627636/b9937d19-a01e-4efb-aaf8-71a9600b1c94)

If this is not in the telegraph, then maybe someone solved it temporarily...

**Comment by fabio-ivona** [comment]
@Freshblood1121 you can start handling it in your webhook handler and then call the controller from it

I'm not sure exposing the controller name is a good idea here

**Comment by fabio-ivona** [comment]
I can't see the code, but I guess this could be optimized 

anyway in V2 I'm planning to add a router for telegraph to handle such cases
