### ISSUE TITLE
How handle url get parametr

### ISSUE THREAD

**Issue by nekithh** [defstudio/telegraph#610]
https://t.me/online_fitness_club_bot?start=dHEzYWtCbm5peGswVzVpUWRTNGtqdz09OjqlXjvCC4+A2ixZFZ312dl
I follow this link and I need to somehow get this token after ?start= and for example put it in the database.
how can i do this?

**Comment by nekithh** [comment]
after following the link and pressing the start*

**Comment by fabio-ivona** [comment]
Hi @nekithh could you dump the message you received from telegram in your webook handler after a user follow that link?

**Comment by nekithh** [comment]
the problem was in the length of the token passed to the get parameter of the bot
