### ISSUE TITLE
Error Handeling Issue

### ISSUE THREAD

**Issue by ah-rahimi** [defstudio/telegraph#620]
You added a try-catch in the `handle` function to prevent the app from crashing if an exception occurs. However, when the chat has not been set yet and an exception is thrown, another exception arises. 

For instance, in issue #619, the `handleMessage()` function hasn't run yet, and an exception is thrown related to `first_name`. In the catch, you're using the `reply()` function to send a message to the user. and the `reply()` function requires a chat to send the message, and since the chat is not found, it leads to another exception.

![image](https://github.com/user-attachments/assets/83960998-b874-4113-8736-f603a7916f95)
_Typed property DefStudio\Telegraph\Handlers\WebhookHandler::$chat must not be accessed before initialization_

**Comment by fabio-ivona** [comment]
fixed
