### ISSUE TITLE
Как работать с сообщения от пользователей

### ISSUE THREAD

**Issue by tokensave** [defstudio/telegraph#644]
У меня есть кнопки с действиями в Handler
    public function addNumbers()
    {
        $this->chat
            ->message('<b>Выберете провайдера</b>')
            ->keyboard(
                Keyboard::make()->buttons(
                    [
                        Button::make('🔵 Telegram')->action('addNumbersSalesmen')->param('name', 1),
                        Button::make('🟢 WhatsApp')->action('addNumbersSalesmen')->param('name', 2),
                    ])
            )
            ->send();
    }
    как мне в функции addNumbersSalesmen добавить возможность написания от клиента его номера для обработки
    не могу пока понять где это в документации
    пожалуйста подскажите
    пишу на фрейморвке ларавел

**Comment by fabio-ivona** [comment]
We do not speak your language, sorry 

Open a new issue in English, please
