### ISSUE TITLE
Is it possible to customize the width of buttons in a row as follows?

### ISSUE THREAD

**Issue by component6** [defstudio/telegraph#676]
4 buttons in one row:
1 and 3 buttons are 40% wide each.
2 and 4 buttons are 10% wide each.

I can't do it, all 4 buttons are displayed with 25% width each

```
use DefStudio\Telegraph\Keyboard\Button;
use DefStudio\Telegraph\Keyboard\Keyboard;

$buttons = [
    Button::make('40%')->width(0.4),
    Button::make('10%')->width(0.1),
    Button::make('40%')->width(0.4),
    Button::make('10%')->width(0.1),
];

$keyboard = Keyboard::make();
$keyboard->buttons($buttons);
```

**Comment by MarioGattolla** [comment]
Hi @component6 , the “width” method does not determine the true width of the buttons , but the amount of buttons in a row. 

Assuming that the maximum width of a row is 1 , you can enter up to 10 buttons with width 0.1, 5 buttons with width 0.2 etc...

In your example all the buttons fit in one row. Unfortunately, Telegram does not allow you to change the width of the individual button

Let me know if anything is not clear

**Comment by component6** [comment]
Thank you. The answer is clear.
